### ISSUE TITLE
Create Lab Diagrams

### ISSUE THREAD

**Issue by supertylerc** [supertylerc/jncip-dc-notes#27]
Create a diagram for each of the labs in the [Labs project](https://github.com/supertylerc/jncip-dc-notes/projects/3).

- [ ] [DCI with VxLAN EVPN and QFX Lab](https://github.com/supertylerc/jncip-dc-notes/issues/15)
- [ ] [Multicast and CRB with QFX Lab](https://github.com/supertylerc/jncip-dc-notes/issues/4)
- [ ] [DCI with VxLAN EVPN and MX Series Lab](https://github.com/supertylerc/jncip-dc-notes/issues/14)
- [ ] [Multicast and CRB with MX Lab](https://github.com/supertylerc/jncip-dc-notes/issues/5)
- [ ] [Multicast and ERB Lab](https://github.com/supertylerc/jncip-dc-notes/issues/6)
- [ ] [EVPN and CRB with QFX Lab](https://github.com/supertylerc/jncip-dc-notes/issues/7)
- [ ] [DCI with MX Series L3VPN Lab](https://github.com/supertylerc/jncip-dc-notes/issues/13)
- [ ] [EVPN and CRB with MX Lab](https://github.com/supertylerc/jncip-dc-notes/issues/8)
- [ ] [DCI with MX Series EVPN Stitching](https://github.com/supertylerc/jncip-dc-notes/issues/12)
- [ ] [EVPN Multihoming with MX Lab](https://github.com/supertylerc/jncip-dc-notes/issues/11)
- [ ] [EVPN Multihoming with QFX Lab](https://github.com/supertylerc/jncip-dc-notes/issues/10)
- [ ] [EVPN and ERB Lab](https://github.com/supertylerc/jncip-dc-notes/issues/9)
